export const TRIP_CATEGORIES = [
  'Adventure',
  'Cultural',
  'Relaxation',
  'Wildlife',
  'Beach',
  'Mountain',
  'Road Trip',
  'Spiritual',
  'Trek',
  'Desert',
  'Historical',
  'Camping',
  'Other',
] as const